### PR TITLE
:bug: analysis-id no longer added to qodana send args when the ID is empty

### PR DESCRIPTION
**Pull request by EGBland**
# Pull Request Details

When the command-line argument string is generated for the publication step of `qodana send`, an empty analysis ID in the options would before result in a malformed argument string, whereas it will now result in the whole argument (name and value) being omitted.

Before this change, an empty analysis ID would result in the argument string containing something like this:

`... --analysis-id --sources-path . ...`

After this change, an empty analysis ID results in:

`... --sources-path . ...`

## Related Issue

See [QD-9111](https://youtrack.jetbrains.com/issue/QD-9111/Missing-analysis-id-in-qodana-send).

## Motivation and Context

I (and my colleagues) have been unable to publish locally-created Qodana results to the cloud. The origin of the problem was due to our empty analysis ID causing a generated command-line argument string to be malformed, resulting in a misleading error reading "Error: Got unexpected extra argument (.)".

This fix has resolved this, by omitting the argument name when the ID is empty.

## How Has This Been Tested

I successfully published my results to our cloud instance. I also ran the tests in `platform/publisher_test.go`, and wrote an additional test.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [**CONTRIBUTING**](https://github.com/JetBrains/qodana-cli/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit messages are styled with [gitmoji](https://gitmoji.dev)
- [ ] My change requires a change to the [documentation](https://jetbrains.com/help/qodana).
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by hybloid** [comment]
@EGBland thanks for your PR. 

May I ask you which exactly linter are you using? Since 233 version we do publish reports to the cloud during the analysis, so there is no need to run CLI command to publish the report you have. 

`--analysis-id` parameter is required here, since we use it to distinguish between duplicates and discard it during publishing if report with the same guid was published.

**Comment by EGBland** [comment]
@hybloid We've been using the .NET linter, running through `qodana scan`; even when we provide the cloud token to `scan`, the report would not be uploaded, hence our workaround of using `qodana send` afterward.

Since the report uploaded successfully without an analysis-id I had assumed it was an optional argument, thank you for clarifying its purpose. Should the analysis ID be generated automatically (suggesting a problem on our end), or should we provide it manually?

**Comment by architectbat** [comment]
@EGBland could you please provide me with the logs (you could just capture the otuput of qodana scan command)? And what is the version of Qodana CLI are you using?

**Comment by hybloid** [comment]
@EGBland could you please provide me with the logs (you could just capture the otuput of qodana scan command)? And what is the version of Qodana CLI are you using?

**Comment by hybloid** [comment]
@EGBland what I did right now:
1 - downloaded and installed latest qodana-cli
2 - launched it with some specific linter (qodana scan --linter jetbrains/qodana-dotnet:latest) in the folder (--ide QDNET would also work, but I am on Mac)
3 - after analysis was finished, right after the table with the results I get the line with the URL of the report.
`/  [6/7] Preparing the report... (56s)The report is uploaded to ....`

Could you please confirm that the same works for you?

**Comment by EGBland** [comment]
@hybloid Apologies for the late reply, we had a long weekend in England.

I will try following your steps and let you know the results.

**Comment by EGBland** [comment]
@hybloid I recreated your instructions as best I could and got the expected behaviour.

I used 2024.1.6, set the `QODANA_TOKEN` env var appropriately, and ran `qodana scan --ide QDNET`; once it finished and it prompted me to view the report I hit "Y" and it took me to the correct report page on our Qodana cloud page.

Thank you for your help. I'm not sure what our initial issue was but I can't recreate it now.

**Pull request closed without merging**
